### ISSUE TITLE
Ayato E Not Intuitive

### ISSUE THREAD

**Issue by malinzoe** [thisRaptori/genshin-rotation-app#38]
Hi there, I am not sure if I am missing something. But to input Ayato E, I had to first put in E skill and then spam normal/charged attacks until they turned grey. There indicator for his E duration showed a way too short duration (I think that only happens when you don't put him first) and I had to just input loads of normal attacks to see how long it lasts. That wasn't very intuitive and involved a lot of clicking. Is there maybe a way to do something like Neuviellettes judgment attack? So when you select Ayato E it shows the right duration and then you can select under normal attacks/his E to do the special attack for the entire duration.

Honestly this little app is so helpful, thank you for all the time and effort put into it!

**Comment by thisRaptori** [comment]
Hey! Yeah the duration indicator just showed the "official" duration for his water illusion as described in the wiki - I think you're right that that's slightly misleading, since it doesn't quite match up to the skill duration in-game 🤔 

I've added a third option to his normal attacks just like Neuvillette's ones, which should do what you suggested! 🎉 

![image](https://github.com/thisRaptori/genshin-rotation-app/assets/19466326/db567b38-f15d-49d3-b58f-dbd9080ed7d8)
